server:
  port: 9007
spring:
  application:
    name: gatewayServer
  cloud:
    gateway:
      routes:
      - id: limit_route
        uri: http://127.0.0.1:9102/
        predicates:
        - After=2017-01-20T17:42:47.789-07:00[America/Denver]
        filters:
        - name: RequestRateLimiter
          args:
            key-resolver: '#{@hostAddrKeyResolver}'
            redis-rate-limiter.replenishRate: 1
            redis-rate-limiter.burstCapacity: 1
    bus:
      trace:
        enabled: true
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
  rabbitmq:
    host: 127.0.0.1
    port: 5672
  zipkin:
    base-url: http://127.0.0.1:9106/
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1.0
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9101/eureka/